
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.0"


target 'WVRNet' do
    
    pod 'AFNetworking',             '~> 3.0'
    pod 'YYModel',                  '~> 1.0'
    pod 'ReactiveObjC',             '~> 3.0'
    
end



